[package]
name = "chalk-parse"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
build = "build.rs" # LALRPOP preprocessing

# Add a dependency on the LALRPOP runtime library:
[dependencies.lalrpop-util]
version = "0.14"
 
[build-dependencies.lalrpop]
version = "0.14"

[dependencies]
error-chain = "0.11.0"
lalrpop-intern = "0.14"
regex = "0.2.2"
