[package]
name = "chalk-parse"
version = "0.1.0"
description = "Parser for the Chalk project"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang-nursery/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]
build = "build.rs" # LALRPOP preprocessing
edition = "2018"

# Add a dependency on the LALRPOP runtime library:
[dependencies.lalrpop-util]
version = "0.16"

[build-dependencies.lalrpop]
version = "0.16"

[dependencies]
error-chain = "0.12.0"
lalrpop-intern = "0.15.1"
regex = "1.0.5"
