language: rust
cache: cargo

rust:
  - stable
  - nightly

script:
  - cd chalk-engine && cargo build --no-default-features && cd ..
  - cd chalk-engine && cargo build --all-features && cd ..
  - cargo test --all
  - cargo doc --all --document-private-items

matrix:
  include:
    - rust: stable
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check

deploy:
  - provider: pages
    local-dir: ./target/doc
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
