language: rust
rust:
  - beta
  - nightly
script:
  - cd chalk-engine; RUSTC_BOOTSTRAP=1 cargo build --no-default-features
  - cd chalk-engine; RUSTC_BOOTSTRAP=1 cargo build --all-features
  - RUSTC_BOOTSTRAP=1 cargo test --all

