language: rust
rust:
  - beta
  - nightly
cache: cargo
script:
  # RUSTC_BOOTSTRAP enables e.g. #![feature] on beta
  - rustup component add rustfmt
  - cd chalk-engine && RUSTC_BOOTSTRAP=1 cargo build --no-default-features && cd ..
  - cd chalk-engine && RUSTC_BOOTSTRAP=1 cargo build --all-features && cd ..
  - cargo fmt --all -- --check
  - RUSTC_BOOTSTRAP=1 cargo test --all
  - RUSTC_BOOTSTRAP=1 cargo doc --all --document-private-items
deploy:
  - provider: script
    script: mkdir -p target/gh-pages && mv target/doc target/gh-pages/
    skip-cleanup: true
    on:
      branch: master
  - provider: pages
    local-dir: ./target/gh-pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
