language: rust
rust:
  - beta
  - nightly
script:
  - cd chalk-engine; RUSTC_BOOTSTRAP=1 cargo build --no-default-features
  - cd chalk-engine; RUSTC_BOOTSTRAP=1 cargo build --all-features
  - RUSTC_BOOTSTRAP=1 cargo test --all
  - RUSTC_BOOTSTRAP=1 cargo doc --document-private-items
deploy:
  provider: pages
  local-dir: ./target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
