[package]
name = "chalk-engine"
version = "0.4.0"
description = "Core trait engine from Chalk project"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang-nursery/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]

[dependencies]
stacker = "0.1.2"
fxhash = "0.2.1"

[dependencies.chalk-macros]
version = "0.1.0"
path = "../chalk-macros"
