[package]
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
name = "chalk-engine"
version = "0.1.0"

[dependencies]
diff = "0.1.11"
docopt = "0.8.1"
ena = "0.4"
error-chain = "0.11.0"
itertools = "0.6.0"
lalrpop-intern = "0.14"
lazy_static = "0.2.2"
petgraph = "0.4.5"
rustyline = "1.0"
serde = "1.0"
serde_derive = "1.0"
stacker = "0.1.2"

[dependencies.chalk-macros]
path = "../chalk-macros"
