[package]
name = "chalk-ir"
version = "0.10.0"
description = "Chalk's internal representation of types, goals, and clauses"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]
edition = "2018"

[dependencies]
lalrpop-intern = { version = "0.15.1", optional = true }

chalk-macros = { version = "0.10.0", path = "../chalk-macros" }
chalk-derive = { version = "0.10.0", path = "../chalk-derive" }
chalk-engine = { version = "0.10.0", path = "../chalk-engine" }

[features]
default = []
default-interner = ["lalrpop-intern"]