[package]
name = "chalk-ir"
version = "0.1.0"
description = "Chalk's internal representation of types, goals, and clauses"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang-nursery/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]

[dependencies]
lalrpop-intern = "0.15.1"

[dependencies.chalk-macros]
version = "0.1.0"
path = "../chalk-macros"

[dependencies.chalk-engine]
version = "0.8.0"
path = "../chalk-engine"
