[package]
name = "chalk"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[workspace]

[lib]
doctest = false

[dependencies]
lalrpop-intern = "0.12.1"
chalk-parse = { path = "../chalk-parse" }
ena = "0.1"